version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:17-jdk
    steps:
      - checkout
      - run:
          name: Build and Test
          command: |
            ./mvnw clean package
